using Anansi.Domain.Enums;

namespace Anansi.Application.DTOs.Presets;

public record EditingPresetDto(
    Guid Id,
    Guid? PhotographerId,
    string Name,
    string? Description,
    SkinToneRange SkinToneRange,
    ShootingContext ShootingContext,
    bool IsPublic,
    bool IsSystemPreset,
    int FavoriteCount,
    bool IsFavorited,
    double Temperature,
    double Tint,
    double Exposure,
    double Contrast,
    double Highlights,
    double Shadows,
    double Whites,
    double Blacks,
    double Clarity,
    double Vibrance,
    double Saturation,
    string HslAdjustments,
    double SplitToneHighlightHue,
    double SplitToneHighlightSaturation,
    double SplitToneShadowHue,
    double SplitToneShadowSaturation,
    DateTime CreatedAt,
    DateTime UpdatedAt);

public record EditingPresetSummaryDto(
    Guid Id,
    Guid? PhotographerId,
    string Name,
    string? Description,
    SkinToneRange SkinToneRange,
    ShootingContext ShootingContext,
    bool IsPublic,
    bool IsSystemPreset,
    int FavoriteCount,
    bool IsFavorited,
    DateTime CreatedAt);

public record CreateEditingPresetRequest(
    string Name,
    string? Description,
    SkinToneRange SkinToneRange,
    ShootingContext ShootingContext,
    bool IsPublic,
    double Temperature,
    double Tint,
    double Exposure,
    double Contrast,
    double Highlights,
    double Shadows,
    double Whites,
    double Blacks,
    double Clarity,
    double Vibrance,
    double Saturation,
    string? HslAdjustments,
    double SplitToneHighlightHue,
    double SplitToneHighlightSaturation,
    double SplitToneShadowHue,
    double SplitToneShadowSaturation);

public record UpdateEditingPresetRequest(
    string Name,
    string? Description,
    SkinToneRange SkinToneRange,
    ShootingContext ShootingContext,
    bool IsPublic,
    double Temperature,
    double Tint,
    double Exposure,
    double Contrast,
    double Highlights,
    double Shadows,
    double Whites,
    double Blacks,
    double Clarity,
    double Vibrance,
    double Saturation,
    string? HslAdjustments,
    double SplitToneHighlightHue,
    double SplitToneHighlightSaturation,
    double SplitToneShadowHue,
    double SplitToneShadowSaturation);
